// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ConversationMessagesListController from "./conversation_messages_list_controller"
application.register("conversation-messages-list", ConversationMessagesListController)

import CopyToClipboardController from "./copy_to_clipboard_controller"
application.register("copy-to-clipboard", CopyToClipboardController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MessageFormController from "./message_form_controller"
application.register("message-form", MessageFormController)

import SubmitOnCmdEnterController from "./submit_on_cmd_enter_controller"
application.register("submit-on-cmd-enter", SubmitOnCmdEnterController)
