---
test:
  host: dashboardchatbot.com.test
  admin_email: it@dashboardchatbot.com
  google_auth:
    client_id: "GOOGLE_AUTH_CLIENT_ID"
    client_secret: "GOOGLE_AUTH_CLIENT_SECRET"
  mini_graphite:
    mock_mode: true
    debug_mode:
  smtp:
    enabled: false
  api:
    admin_token:
      - TEST_ADMIN_TOKEN_1
      - TEST_ADMIN_TOKEN_2
    token:
      - TEST_TOKEN_1
      - TEST_TOKEN_2
  captcha:
    site_key: "SITE_KEY"
    secret_key: "SECRET_KEY"
  opentelemetry:
    traces_exporter: "none"
  dashboard_db_connection: "sqlite://<%= Rails.root %>/csv_db/dashboard.test.sqlite3"
  openai_api_key: "<%= Rails.application.credentials.openai_api_key %>"

development:
  host: dashboardchatbot.com.pizza
  admin_email: it@dashboardchatbot.com
  google_auth:
    client_id: "<%= Rails.application.credentials.google_auth.client_id %>"
    client_secret: "<%= Rails.application.credentials.google_auth.client_secret %>"
  mini_graphite:
    mock_mode: true
    debug_mode: true
  smtp:
    enabled: false
  api:
    admin_token:
      - "<%= Rails.application.credentials.api_admin_token %>"
    token:
      - "<%= Rails.application.credentials.app_token %>"
  captcha:
    site_key: "<%= Rails.application.credentials.captcha.site_key %>"
    secret_key: "<%= Rails.application.credentials.captcha.secret_key %>"
  opentelemetry:
    traces_exporter: "none" # console
  dashboard_db_connection: "sqlite://<%= Rails.root %>/csv_db/dashboard.development.sqlite3"
  openai_api_key: "<%= Rails.application.credentials.openai_api_key %>"

production:
  host: dashboardchatbot.com
  admin_email: it@dashboardchatbot.com
  google_auth:
    client_id: "<%= Rails.application.credentials.google_auth.client_id %>"
    client_secret: "<%= Rails.application.credentials.google_auth.client_secret %>"
  mini_graphite:
    graphite_host: 10.0.0.44
    graphite_port: 2003
    statsd_host: 10.0.0.44
    statsd_port: 8125
    mock_mode: false
    debug_mode: false
  api:
    admin_token:
      - "<%= Rails.application.credentials.api_admin_token %>"
    token:
      - "<%= Rails.application.credentials.app_token %>"
  captcha:
    site_key: "<%= Rails.application.credentials.captcha.site_key %>"
    secret_key: "<%= Rails.application.credentials.captcha.secret_key %>"
  opentelemetry:
    traces_exporter: "otlp"
    otlp_endpoint: "http://otelcollector.railsskeleton.com:14318"
  dashboard_db_connection: "sqlite://<%= Rails.root %>/csv_db/dashboard.sqlite3"
  openai_api_key: "<%= Rails.application.credentials.openai_api_key %>"
