---
test:
  host: railsskeleton.com.test
  admin_email: it@railsskeleton.com
  google_auth:
    client_id: "GOOGLE_AUTH_CLIENT_ID"
    client_secret: "GOOGLE_AUTH_CLIENT_SECRET"
  mini_graphite:
    mock_mode: true
    debug_mode:
  smtp:
    enabled: false
  api:
    admin_token:
      - TEST_ADMIN_TOKEN_1
      - TEST_ADMIN_TOKEN_2
    token:
      - TEST_TOKEN_1
      - TEST_TOKEN_2
  captcha:
    site_key: "SITE_KEY"
    secret_key: "SECRET_KEY"
  opentelemetry:
    traces_exporter: "none"

development:
  host: railsskeleton.com.pizza
  admin_email: it@railsskeleton.com
  google_auth:
    client_id: "<%= ENV.fetch('GOOGLE_AUTH_CLIENT_ID') %>"
    client_secret: "<%= ENV.fetch('GOOGLE_AUTH_CLIENT_SECRET') %>"
  mini_graphite:
    mock_mode: true
    debug_mode: true
  smtp:
    enabled: false
  api:
    admin_token:
      - "<%= ENV.fetch('API_ADMIN_TOKEN') %>"
    token:
      - "<%= ENV.fetch('APP_TOKEN') %>"
  captcha:
    site_key: "<%= ENV.fetch('CAPTCHA_SITE_KEY') %>"
    secret_key: "<%= ENV.fetch('CAPTCHA_SECRET_KEY') %>"
  opentelemetry:
    traces_exporter: "none" # console

staging:
  host: staging.railsskeleton.com
  admin_email: it@railsskeleton.com
  google_auth:
    client_id: "<%= ENV.fetch('GOOGLE_AUTH_CLIENT_ID') %>"
    client_secret: "<%= ENV.fetch('GOOGLE_AUTH_CLIENT_SECRET') %>"
  mini_graphite:
    graphite_host: 10.0.128.44
    graphite_port: 2003
    statsd_host: 10.0.128.44
    statsd_port: 8125
    mock_mode: false
    debug_mode: true
  api:
    admin_token:
      - "<%= ENV.fetch('API_ADMIN_TOKEN') %>"
    token:
      - "<%= ENV.fetch('APP_TOKEN') %>"
  captcha:
    site_key: "<%= ENV.fetch('CAPTCHA_SITE_KEY') %>"
    secret_key: "<%= ENV.fetch('CAPTCHA_SECRET_KEY') %>"
  opentelemetry:
    traces_exporter: "otlp"
    otlp_endpoint: "http://otelcollector.zebra.town:14318"

production:
  host: railsskeleton.com
  admin_email: it@railsskeleton.com
  google_auth:
    client_id: "<%= ENV.fetch('GOOGLE_AUTH_CLIENT_ID') %>"
    client_secret: "<%= ENV.fetch('GOOGLE_AUTH_CLIENT_SECRET') %>"
  mini_graphite:
    graphite_host: 10.0.0.44
    graphite_port: 2003
    statsd_host: 10.0.0.44
    statsd_port: 8125
    mock_mode: false
    debug_mode: false
  api:
    admin_token:
      - "<%= ENV.fetch('API_ADMIN_TOKEN') %>"
    token:
      - "<%= ENV.fetch('APP_TOKEN') %>"
  captcha:
    site_key: "<%= ENV.fetch('CAPTCHA_SITE_KEY') %>"
    secret_key: "<%= ENV.fetch('CAPTCHA_SECRET_KEY') %>"
  opentelemetry:
    traces_exporter: "otlp"
    otlp_endpoint: "http://otelcollector.zebra.town:14318"
