default: &default
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_bin
  username: root
  password: <%= Rails.application.credentials.rails_db_password %>
  host: 127.0.0.1
  port: 3306

development:
  <<: *default
  database: dashboardchatbot_development

test:
  <<: *default
  database: dashboardchatbot_test

production:
  <<: *default
  host: db
  database: dashboardchatbot
  password: root
