test:
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_bin
  database: scrapstatsv2_test
  username: root
  password: <%= ENV.fetch('SECRET_RAILS_DB_PASSWORD') %>
  host: 127.0.0.1

development:
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_bin
  database: scrapstatsv2_development
  username: root
  password: <%= ENV.fetch('SECRET_RAILS_DB_PASSWORD') %>
  host: 127.0.0.1

production:
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_bin
  host: db-scrapstatsv2-production.network
  port: 3306
  database: scrapstatsv2_production
  username: root
  password: <%= ENV.fetch('SECRET_RAILS_DB_PASSWORD') %>

staging:
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_bin
  host: db-scrapstatsv2-staging.network
  port: 3306
  database: scrapstatsv2_staging
  username: root
  password: <%= ENV.fetch('SECRET_RAILS_DB_PASSWORD') %>
