default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: postgres
  password: postgres

development:
  <<: *default
  database: dashboardchatbot_development

test:
  <<: *default
  database: dashboardchatbot_test

production:
  <<: *default
  host: db
  database: dashboardchatbot
  password: root
