FROM ruby:3.2.4-alpine3.19

# Install dependencies
RUN apk update --no-cache
RUN apk upgrade

RUN apk add --no-cache build-base git curl
RUN apk add --no-cache bash libstdc++ zlib pkgconfig autoconf automake libtool nasm
RUN apk add --no-cache tzdata nodejs npm openjdk8 libxml2 libxslt gcompat imagemagick
RUN apk add --no-cache gifsicle jpegoptim libpng libjpeg-turbo libjpeg-turbo-utils optipng pngcrush pngquant
RUN apk add --no-cache advancecomp --repository http://dl-cdn.alpinelinux.org/alpine/edge/community
RUN apk add --no-cache jhead --repository http://dl-cdn.alpinelinux.org/alpine/edge/testing
RUN npm install -g --force --unsafe-perm=true --allow-root svgo advpng-bin
RUN apk add --update --no-cache openssh

# For mysql
RUN apk add --no-cache mariadb-dev

# Install postgresql dependencies
RUN apk add libpq-dev

# Set an environment variable where the Rails app is installed to inside of Docker image:
ENV RAILS_ROOT /var/www/app
RUN mkdir -p $RAILS_ROOT

# Set working directory, where the commands will be ran:
WORKDIR $RAILS_ROOT

# Setting env up
ENV RAILS_ENV="production"
ENV RACK_ENV="production"

# Basic folders (required by puma)
RUN mkdir -p tmp/pids
RUN mkdir -p tmp/sockets

# Adding gems
COPY Gemfile Gemfile
COPY Gemfile.lock Gemfile.lock

RUN bundle install --jobs 2 --retry 2 --without development test

# Adding project files
COPY . .
# RUN bundle exec rails assets:precompile

## Cron config

# In alpine we have a cron file per user. We have to reuse the actual
#  one and add our crons
COPY crontab /tmp
RUN cat /tmp/crontab >> /etc/crontabs/root && rm /tmp/crontab

# To load the env variables in cron sessions
# without this the user in the cron session won't be able to find commands and Gems
RUN printenv | grep -v "no_proxy" >> /etc/environment

# Run the command on container startup
CMD ["crond", "-f"]
